{% set version = "2.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggrandomforests
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggRandomForests_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggRandomForests/ggRandomForests_{{ version }}.tar.gz
  sha256: 8725e52ba6bae632ca414d5c22ea27972421590d5a8c96832cd28a5781ce8117

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-randomforest
    - r-randomforestsrc >=1.5.5
    - r-survival
    - r-tidyr
  run:
    - r-base
    - r-ggplot2
    - r-randomforest
    - r-randomforestsrc >=1.5.5
    - r-survival
    - r-tidyr

test:
  commands:
    - $R -e "library('ggRandomForests')"           # [not win]
    - "\"%R%\" -e \"library('ggRandomForests')\""  # [win]

about:
  home: https://github.com/ehrlinger/ggRandomForests
  license: GPL-3.0-or-later
  summary: Graphic elements for exploring Random Forests using the 'randomForest' or 'randomForestSRC' package for survival, regression and classification forests and 'ggplot2' package plotting.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
